### ISSUE TITLE
Chapter 2, Mandelbrot example, inconsistent result for OpenACC on PGI

### ISSUE THREAD

**Issue by gtelzur** [OpenACCUserGroup/openacc_concept_strategies_book#2]
## Chapter 2, Mandelbrot example:
Accelerator version using PGI compiler gives a different result than the same code using gcc8  (for both  openmp and nvptx+acc), pgi using openmp and the serial pgi, see results below:
tests> ./area.gcc.acc 
Area of Mandlebrot set =   1.50787863 +/-   0.00037697
Time taken for calculation: 35.649632
tests> ./area.gcc.omp 
Area of Mandlebrot set =   1.50787371 +/-   0.00037697
Time taken for calculation: 37.912720 on 8 threads
tests> ./area.pgi.omp 
Area of Mandlebrot set =   1.50787863 +/-   0.00037697
Time taken for calculation: 27.200890 on 8 threads
**tests> ./area.pgi.acc 
Area of Mandlebrot set =   2.98259191 +/-   0.00074565
Time taken for calculation: 15.394787**
tests> ./area.pgi.ser 
Area of Mandlebrot set =   1.50787863 +/-   0.00037697
Time taken for calculation: 81.918041
tests> 

Moreover, the pgi+acc version results are not stable, upon repeating the execution several times, different results were obtained:

tests> ./area.pgi.acc 
Area of Mandlebrot set =   5.19458836 +/-   0.00129865
Time taken for calculation: 15.496788
tests> ./area.pgi.acc 
Area of Mandlebrot set =   1.87656363 +/-   0.00046914
Time taken for calculation: 15.315470
tests> ./area.pgi.acc 
Area of Mandlebrot set =   3.35120801 +/-   0.00083780
Time taken for calculation: 15.405854
tests> 

The tests took place on an Asus laptop with 16GB RAM, i7 CPU, nvidia GeForce GTX-1050 GPU and Linux Mint.

Regards,

Guy Tel-Zur

**Comment by adrianjhpc** [comment]
Thanks for the feedback.  Can you let us know if this is the Fortran or C version of the source code?  Which version of the PGI compiler are you using?

**Comment by adrianjhpc** [comment]
I've updated the code with a fix for this issue, can you re-run with the latest code and let me know if you still see the variable result?

**Comment by gtelzur** [comment]
I am referring to the C version and the version of PGI is: pgilinux-2017-174-x86_64.
I will re-run the examples within a few days.

Good luck

Guy
